CREATE OR REPLACE FUNCTION NbCustOfSalesPerson(P_EMPID IN EMPLOYEE.EMPLOYEE_ID%TYPE) RETURN NUMBER
IS
V_COUNT NUMBER;

BEGIN
    SELECT COUNT(*) INTO V_COUNT 
    FROM CUSTOMER
    WHERE SALESPERSON_ID=P_EMPID;
    RETURN V_COUNT; 
END;    